title: Hello World!
author: Yvette Banuelos Arriaga 
email: ybanuelog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Okay, this is like the fifth time I've had to do this.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
