title: Hello World!
author: Yvette Banuelos Arriaga
email: ybanuelosg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Okay, so I said the last blog was going to be my only blog 
  but that didn't work out so lets pretend this is the first
  time you are seeing this...

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-midnight
